services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: dotnet_sdk
    ports:
      - "5000:5015" # Port pour l'application ASP.NET Core
      - "5001:5001" # Port HTTPS si nécessaire
    volumes:
      - ./part1:/app1 # Monte le dossier app local dans le conteneur
    stdin_open: true
    tty: true # Permet de garder le conteneur interactif pour les commandes
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.50' # Limite l'utilisation du CPU à 50%
          memory: 512M # Limite l'utilisation de la mémoire à 512MB
  spring-app:
    image: openjdk:17-jdk-slim
    container_name: spring_app
    build:
      context: ./part2/projets5 # Chemin vers le projet Spring (contenant le Dockerfile)
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Port exposé pour l'application Spring Boot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud
      - SPRING_DATASOURCE_USERNAME=backend
      - SPRING_DATASOURCE_PASSWORD=sql
    volumes:
      - ./part2:/app2 # Monte le code source dans le conteneur
      - ~/.m2/repository:/root/.m2/repository
    working_dir: /app2
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.50'

  react-app:
    container_name: react_app
    build:
      context: ./part3/front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./part3:/app3
    restart: always


  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=backend  # Utilisateur PostgreSQL
      - POSTGRES_PASSWORD=sql # Mot de passe PostgreSQL
      - POSTGRES_DB=cloud  # Nom de la base de données par défaut
    ports:
      - "5433:5432"  # Port de PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data:rw  # Persiste les données de la base de données PostgreSQL
      - ./ressources:/docker-entrypoint-initdb.d # Monte le dossier ressources contenant le script SQL
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50' # Limite l'utilisation du CPU à 50%
          memory: 512M # Limite l'utilisation de la mémoire à 512MB

volumes:
  pgdata: